### ISSUE TITLE
cannot resolve dependency

### ISSUE THREAD

**Issue by abhishzk** [novatorem/Website#2]
Abhisheks-MBP Website % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: andrewnovac@1.0.0
npm ERR! Found: gatsby@2.22.4
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"2.22.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^5.0.0" from gatsby-plugin-robots-txt@1.8.0
npm ERR! node_modules/gatsby-plugin-robots-txt
npm ERR!   gatsby-plugin-robots-txt@"^1.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/akumar/.npm/_logs/2023-02-07T13_51_39_894Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akumar/.npm/_logs/2023-02-07T13_51_39_894Z-debug-0.log
[2023-02-07T13_51_39_894Z-eresolve-report.txt](https://github.com/novatorem/Website/files/10675694/2023-02-07T13_51_39_894Z-eresolve-report.txt)
[2023-02-07T13_51_39_894Z-debug-0.log](https://github.com/novatorem/Website/files/10675698/2023-02-07T13_51_39_894Z-debug-0.log)

**Comment by novatorem** [comment]
There's been a rebuild, switching away from Gatsby and into sveltekit.
The old version won't be supported.
